### ISSUE TITLE
Blank LCSC attribute may lead to JLCPCB specifying an undesired part

### ISSUE THREAD

**Issue by warp929** [oxullo/jlcpcb-eagle#11]
I’m using the latest version as of November 5, 2022.

I have several objects in my layout that are either not parts or I don’t want JLCPCB to populate them. For example, solder jumpers and fiducials. Unfortunately, due to the way JLCPCB handles the BOM and CPL files they’ll occasionally put a part number in for those solder jumper or fiducials. The system just selects a part number from my BOM.

To avoid this, I have tried to:
1) Not have an LCSC attribute. 
2) Have an LCSC attribute but leave it blank.
3) Have an LCSC attribute at set it to “none”
4) Delete non-components from the BOM and CPL files

Attempts 1-3 all lead to the same problem listed above. Only #4 is a functional solution but time consuming and prone to error if I don’t go line by line on the BOM and CPL file at the same time.

I’d like to request that there be an option to either export all objects or to automatically exclude objects that do not have an LCSC attribute or it is blank.

Your work on this project is much appreciated. Thank you.

**Comment by oxullo** [comment]
Hey @warp929, thanks for the observations.
This is an open issue I tried to tackle with JLCPCB. Testpoints, along fiducials and bridges, should be excluded from the BOM, but their identification is a hassle. As you pointed out, there's no practical way to work around how the ULP works, so this should be addressed by improving the script.

Relying on a pattern test on the parts' designators doesn't sound a good option to me, yet it's the most practical one.
I personally don't use variants, but they'd allow to use the "populate" flag.
Another option: adding an attribute (eg: DNP) to the components that shouldn't be exported to the BOM. This one allows the highest degree of flexibility, it's the least intrusive but it also require manual tagging.
I wouldn't exclude a part just because it doesn't have an LCSC attribute: one might want to be able to search for the part manually (and eventually back-annotate the part).

Let me know what you think

**Comment by warp929** [comment]
Thanks for considering my suggestion.  I think having an LCSC attribute and populating that to DNP is a good option. I can set the LCSC/DNP attribute in my Library for fiducials, test points, etc. so it would only be a one time change. Your script, if possible, can then ignore and not export anything with "DNP" in the LCSC attribute.

**Comment by oxullo** [comment]
What if, instead of using the LCSC attribute, an extra one it is introduced eg: "DNP" which, if defined, does not include the part into the bom/cpl?
In this way, the LCSC attribute stays as is (either undefined or defined and valid but for whatever reason not wanted populated) and it's easier to flag in and out a specific part. In particular, it's also possible to set the attribute in the library (for all the TPs, for examples), so it's implicitly not considered when generating.

Have a look at a28bd83, looking forward to your feedback.

**Comment by warp929** [comment]
Hello. I played around with your method of adding a DNP attribute and my method of changing the LCSC attribute value to DNP.  I prefer your method since it keeps the LCSC part number intact. I have connectors that I do not always populate and if I replace the LCSC part number and accidentally save, then I have to find it again. Thank you for all your efforts on this script.

**Comment by oxullo** [comment]
Cool! then I merge ;)
